<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '071d904d7e9f67639b5e5bc65c2988dc' => $baseDir . '/includes/functions/init.php',
);
